## Introduction

This is an introduction to Python notebooks.

In [1]:
print("hello")
print("hello again")
# shift-enter runs this sell
# this is a comment

hello
hello again


In [2]:
a=3

In [3]:
print(a)

3


In [4]:
%whos

Variable   Type    Data/Info
----------------------------
a          int     3


## Variables

In [5]:
weight_kg = 55

In [9]:
print(weight_kg)


55


In [10]:
2.2*weight_kg

121.00000000000001

In [11]:
print("weight in pounds", 2.2*weight_kg)

weight in pounds 121.00000000000001


weight_lb=2.2*weight_kg

In [13]:
print("weight in kg",weight_kg)
print("weight in pounds",weight_lb)

weight in kg 55
weight in pounds 121.00000000000001


In [14]:
weight_kg=100

In [15]:
print("weight in kg",weight_kg)
print("weight in pounds",weight_lb)

weight in kg 100
weight in pounds 121.00000000000001


# Plotting data

In [16]:
import numpy

In [17]:
ls

SC_Python_Programming.ipynb  inflammation-09.csv
inflammation-01.csv          inflammation-10.csv
inflammation-02.csv          inflammation-11.csv
inflammation-03.csv          inflammation-12.csv
inflammation-04.csv          small-01.csv
inflammation-05.csv          small-02.csv
inflammation-06.csv          small-03.csv
inflammation-07.csv          testnotebook.ipynb
inflammation-08.csv


In [18]:
pwd

'/Users/pawelpomorski/Desktop/data'

In [19]:
numpy.loadtxt(fname="inflammation-01.csv",delimiter=",")

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [20]:
data=numpy.loadtxt(fname="inflammation-01.csv",delimiter=",")

In [21]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [22]:
print(type(data))

<class 'numpy.ndarray'>


In [23]:
print(data.shape)

(60, 40)


In [24]:
print(data.dtype)

float64


In [25]:
print(data[0][0])

0.0


In [26]:
print(data[0][3])

3.0


In [27]:
print(data[30][20])

13.0


In [29]:
print(data[0][:])

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


In [30]:
datarow=data[0][:]


In [31]:
print(datarow)

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


In [43]:
datarow.shape

(40,)

In [34]:
print(data[0][10:])

[ 3.  3. 10.  5.  7.  4.  7.  7. 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.
  8.  8.  4.  4.  5.  7.  3.  4.  2.  3.  0.  0.]


In [35]:
print(data[0:4][0:4])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
   2.  3.  0.  0.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7. 10.  7.  9. 13.  8.  8. 15. 10.
  10.  7. 17.  4.  4.  7.  6. 15.  6.  4.  9. 11.  3.  5.  6.  3.  3.  4.
   2.  3.  2.  1.]]


In [36]:
print(data[:4][:4])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
   2.  3.  0.  0.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7. 10.  7.  9. 13.  8.  8. 15. 10.
  10.  7. 17.  4.  4.  7.  6. 15.  6.  4.  9. 11.  3.  5.  6.  3.  3.  4.
   2.  3.  2.  1.]]


In [38]:
print(data[-1][:])

[ 0.  0.  1.  0.  3.  2.  5.  4.  8.  2.  9.  3.  3. 10. 12.  9. 14. 11.
 13.  8.  6. 18. 11.  9. 13. 11.  8.  5.  5.  2.  8.  5.  3.  5.  4.  1.
  3.  1.  1.  0.]


In [39]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [40]:
print(2*data)

[[0. 0. 2. ... 6. 0. 0.]
 [0. 2. 4. ... 2. 0. 2.]
 [0. 2. 2. ... 4. 2. 2.]
 ...
 [0. 2. 2. ... 2. 2. 2.]
 [0. 0. 0. ... 0. 4. 0.]
 [0. 0. 2. ... 2. 2. 0.]]


In [41]:
print(data+data)

[[0. 0. 2. ... 6. 0. 0.]
 [0. 2. 4. ... 2. 0. 2.]
 [0. 2. 2. ... 4. 2. 2.]
 ...
 [0. 2. 2. ... 2. 2. 2.]
 [0. 0. 0. ... 0. 4. 0.]
 [0. 0. 2. ... 2. 2. 0.]]


In [42]:
print(data*data)

[[0. 0. 1. ... 9. 0. 0.]
 [0. 1. 4. ... 1. 0. 1.]
 [0. 1. 1. ... 4. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 4. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [44]:
datarow.shape

(40,)

In [45]:
data.shape

(60, 40)

In [46]:
print(data+datarow)

[[0. 0. 2. ... 6. 0. 0.]
 [0. 1. 3. ... 4. 0. 1.]
 [0. 1. 2. ... 5. 1. 1.]
 ...
 [0. 1. 2. ... 4. 1. 1.]
 [0. 0. 1. ... 3. 2. 0.]
 [0. 0. 2. ... 4. 1. 0.]]


In [47]:
datahalf=datarow[0:20]

In [48]:
datahalf.shape

(20,)

In [49]:
data+datahalf

ValueError: operands could not be broadcast together with shapes (60,40) (20,) 